
package bank.soap.client.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankServiceImpl", targetNamespace = "http://server.soap.bank/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankServiceImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws InactiveException_Exception
     * @throws IOException_Exception
     * @throws OverdrawException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.TransferResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/transferRequest", output = "http://server.soap.bank/BankServiceImpl/transferResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/transfer/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/transfer/Fault/OverdrawException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/transfer/Fault/InactiveException")
    })
    public void transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.CreateAccountResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/createAccountRequest", output = "http://server.soap.bank/BankServiceImpl/createAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/createAccount/Fault/IOException")
    })
    public String createAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeAccount", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.CloseAccount")
    @ResponseWrapper(localName = "closeAccountResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.CloseAccountResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/closeAccountRequest", output = "http://server.soap.bank/BankServiceImpl/closeAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/closeAccount/Fault/IOException")
    })
    public boolean closeAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountNumbers", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.GetAccountNumbers")
    @ResponseWrapper(localName = "getAccountNumbersResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.GetAccountNumbersResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/getAccountNumbersRequest", output = "http://server.soap.bank/BankServiceImpl/getAccountNumbersResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/getAccountNumbers/Fault/IOException")
    })
    public List<String> getAccountNumbers()
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.GetAccountResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/getAccountRequest", output = "http://server.soap.bank/BankServiceImpl/getAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/getAccount/Fault/IOException")
    })
    public String getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isActive", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.IsActive")
    @ResponseWrapper(localName = "isActiveResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.IsActiveResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/isActiveRequest", output = "http://server.soap.bank/BankServiceImpl/isActiveResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/isActive/Fault/IOException")
    })
    public boolean isActive(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InactiveException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deposit", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.DepositResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/depositRequest", output = "http://server.soap.bank/BankServiceImpl/depositResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/deposit/Fault/IOException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/deposit/Fault/InactiveException")
    })
    public void deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws IOException_Exception, InactiveException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InactiveException_Exception
     * @throws IOException_Exception
     * @throws OverdrawException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.WithdrawResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/withdrawRequest", output = "http://server.soap.bank/BankServiceImpl/withdrawResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/withdraw/Fault/IOException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/withdraw/Fault/OverdrawException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/withdraw/Fault/InactiveException")
    })
    public void withdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://server.soap.bank/", className = "bank.soap.client.jaxws.GetBalanceResponse")
    @Action(input = "http://server.soap.bank/BankServiceImpl/getBalanceRequest", output = "http://server.soap.bank/BankServiceImpl/getBalanceResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://server.soap.bank/BankServiceImpl/getBalance/Fault/IOException")
    })
    public double getBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception
    ;

}
